### ISSUE TITLE
Add Feed first iteration

### ISSUE THREAD

**Issue by skempisty** [skempisty/will-call-public#33]
Let's discuss here exactly what should be a part of the feed's first iteration

Feed items:
- My friend is joining me at X event
- X commented on your post
- X replied to your comment

**Comment by skempisty** [comment]
**@andy**

The way i see it roughly is like - notifications are things that happen to me. Like “X followed you” or “X commented on your post”

Whereas feed is activity from people/things you follow. Like “Mohan just joined X event” or “Wong posted”

I’m not too worried about users getting inundated on their feed yet since we’ll prob have the opposite problem of there not being enough activity for them to see. And agree we can tweak later if needed

Later we should prob add feature where they can turn on notifications for certain artists/venues/events. So if you want, you can get notifications like “Artist or Venue announced a new show” or “Event announced set times”

**Comment by mrandypark** [comment]
**FEED**
My friend posted
My friend commented
My friend rated an event
My friend followed a new artist/venue/event


**NOTIFICATIONS**
My friend followed me
Someone commented on my post
Someone replied to my comment
My friend is joining me at an event
An event/venue/artist _that I enabled notifications for_ has new activity

**Comment by MohanMandali** [comment]
Some more thoughts:

**FEED**
(Once we have it) My friend rated with a comment on an event 
My friend followed a new friend (for now as we build users, this is something we can get rid of later) 
My friend posted in an event thread (this is something again we can remove later) 
**NOT MVP**My friend is currently listening to (but it would be cool if we had our way of posting like a music cover or something) 

**NOTIFICATIONS**
**NOT MVP** But at some point it would be cool to @someone, so if its in a comment/thread it gives you a notification
**NOT MVP** If a event your following posts official set times 
**NOT MVP** If a event you follow, the artist posts something official from their account

**Comment by skempisty** [comment]
https://github.com/skempisty/will-call/pull/65
